services:
  database:
    image: postgres:15
    container_name: task-tracker-db
    environment:
      # Берем из локального .env и передаем в Postgres
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      # Используем $$ и внутренние переменные самого Postgres
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    restart: unless-stopped

  app:
    build: .
    container_name: task-tracker-app
    depends_on:
      database:
        condition: service_healthy
    environment:
      # Пробрасываем переменные внутрь Spring Boot приложения
      DB_HOST: database  # Внутри сети Docker хостом БД является имя её сервиса
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      DB_PORT: 5432      # Внутри контейнера порт всегда 5432, а не внешний ${DB_PORT}
    ports:
      - "8080:8080"
    restart: unless-stopped

# Инициализируем именованный том для вечного хранения данных
volumes:
  postgres_data: {}