spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=never
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Время жизни jwt токена
testing.app.lifetime=86400000
# Секретный ключ для JWT токенов
testing.app.secret=MySuperSecretKeyForTaskTrackerApplicationWhichIsVeryLong

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.data.web.pageable.page-serialization-mode=via_dto


# Конфигурация интеграции с Gemini API
spring.ai.google.genai.api-key= ${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-3.5-flash


# Настройки Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=6379
# Включаем кэш
spring.cache.type=redis

# Flyway placeholders
spring.flyway.placeholders.admin_username=${ADMIN_USERNAME}
spring.flyway.placeholders.admin_password_hash=${ADMIN_PASSWORD_HASH}


management.endpoints.web.exposure.include=health,info,metrics,prometheus,flyway,scheduledtasks
management.endpoint.health.show-details=when-authorized
management.metrics.tags.application=task-tracker
